---
# tasks file for ec2

- name: Create EC2 instance
  ec2:
    key_name: my_key
    instance_type: t2.micro
    image: ami-0c55b159cbfafe1f0
    region: us-east-2
    wait: yes
    count: 1
    vpc_subnet_id: subnet-0123456789abcdef0
    assign_public_ip: yes
  register: ec2

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: launched
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    state: started
  with_items: "{{ ec2.instances }}"
